services:
  application:
    container_name: gestao_cursos_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_bridge
  postgres:
    container_name: gestao_cursos_postgres
    image: bitnami/postgresql
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${PG_USER} -d ${PG_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_cursos
    networks:
      - api_bridge
      - sonarqube-network
networks:
  api_bridge:
    driver: bridge
