services:
  postgres:
    env_file:
      - path: .env
    container_name: gestao_cursos_postgres
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    networks:
      - api_bridge
      - sonarqube-network

  sonarqube:
    env_file:
      - path: .env
    container_name: gestao_cursos_sonarqube
    image: sonarqube:9.9.0-community
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_DATABASE_USER=${PG_USER}
      - SONARQUBE_DATABASE_PASSWORD=${PG_PASSWORD}
      - SONARQUBE_DATABASE_NAME=${PG_DB}
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

networks:
  api_bridge:
    driver: bridge
  sonarqube-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
