resilience4j:
  ratelimiter:
    instances:
      universalRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 500ms
        register-health-indicator: true
